name: 'Switch Case Action'
description: 'Checks conditional switch case. to return the value of true condition or default condition.'
author: 'Jirayu S. (WRM Software)'

# Define your inputs here.
inputs:
  default:
    description: The default value to be returned if no conditionals match.
    required: true
  conditionals-with-values:
    description: 'Your input description here'
    required: true

# Define your outputs here.
outputs:
  match:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
